name:                ngram
version:             0.1.0.1
github:              TomLippincott/ngram
license:             BSD3
author:              Tom Lippincott
maintainer:          tom@cs.jhu.edu
copyright:           2018 Tom Lippincott

extra-source-files:
- README.md

synopsis:            Ngram models for compressing and classifying text.
category:            natural-language-processing, machine-learning
description:         A library and collection of commands for training,
                     evaluating, and applying n-gram-based sequence models.
dependencies:
  - base >= 4.7 && < 5
  - text >=1.2.2
  - containers >=0.5.10.2
  - cereal >=0.5.4.0
  - cereal-text >=0.1.0.2
  - logging-effect >=1.3.2
  - mtl >=2.2.2

  
default-extensions:
  - Strict
  - StrictData
  
library:
  source-dirs: src
 
executables:
  ngramClassifier:
    main:                NGramClassifier.hs
    source-dirs:         app
    dependencies:
      - ngram
      - optparse-generic >=1.2.2
      - zlib >=0.6.1
      - bytestring >=0.10.8.1
    ghc-options:
      - -threaded
      