name:                ngram
version:             0.1.0.1
github:              TomLippincott/ngram
license:             BSD3
author:              Tom Lippincott
maintainer:          tom@cs.jhu.edu
copyright:           2018 Tom Lippincott

extra-source-files:
- README.md

synopsis:            Ngram models for compressing and classifying text.
category:            natural-language-processing, machine-learning
description:         A library and collection of commands for training,
                     evaluating, and applying n-gram-based sequence models.
dependencies:
  - base >= 4.7 && < 5
  - text >=1.2.2
  - containers >=0.5.10.2
  - cereal >=0.5.4.0
  - cereal-text >=0.1.0.2
  - logging-effect >=1.3.2
  - mtl >=2.2.2
  - yesod >=1.6.0
  - yesod-core >=1.6.0
  - binary >=0.8.6.0
  - conduit >=1.3.1
  - conduit-extra >=1.3.0
  - http-types >=0.12.2
  - wai >=3.2.1.2
  - aeson >=1.4.2.0
  - unordered-containers >=0.2.9.0
  - store >=0.7.1
  - th-utilities >=0.2.0.1
  - hashable >=1.2.7.0
  - bytestring >=0.10.8.2
  - http-conduit >=2.3.4
  - wai-conduit >=3.0.0.4
  - scientific >=0.3.6.2
  - vector >=0.12.0.2
  - zlib >=0.6.1
  - bytestring >=0.10.8.1
  - deepseq >=1.4.4.0
  - utf8-string >=1.0.1.1
  - base64-bytestring >=1.0.0.2
default-extensions:
  - Strict
  - StrictData
  - OverloadedStrings
  - TypeSynonymInstances
  - FlexibleInstances
  
library:
  source-dirs: src
#  ghc-options:
#    - -prof -rtsopts -auto-all -caf-all
 
executables:
  ngramClassifier:
    main:                NGramClassifier.hs
    source-dirs:         app
    dependencies:
      - ngram
      - optparse-generic >=1.2.2


#    ghc-options:
#      - -prof -rtsopts -auto-all -caf-all
